/**
 * Centralized PWA constants to avoid magic strings, regexes, and duplicated
 * definitions across the codebase.
 */

import { APP_NAME } from './app.constants';

export const MEDIA_QUERIES = {
	DISPLAY_MODE_STANDALONE: '(display-mode: standalone)',
	PREFERS_DARK: '(prefers-color-scheme: dark)',
	PREFERS_LIGHT: '(prefers-color-scheme: light)'
} as const;

export const THEME_COLORS = {
	ACCENT_BLUE: '#2563eb',
	ACCENT_BLUE_HOVER: '#1d4ed8',
	BACKGROUND_DARK: '#111111',
	BACKGROUND_LIGHT: 'white',
	DARK: '#0d0d0d',
	LIGHT: '#ffffff',
	TITLE_UPDATE_ALERT: {
		BG_DARK: 'zinc-800',
		BG_LIGHT: 'white',
		BORDER_DARK: 'zinc-700',
		BORDER_LIGHT: 'zinc-200',
		TEXT_DARK: 'zinc-400',
		TEXT_LIGHT: 'zinc-500'
	}
} as const;

export const FAVICON_PATHS = {
	ICO_DARK: 'favicon-dark.ico',
	ICO_LIGHT: 'favicon.ico',
	SVG_DARK: 'favicon-dark.svg',
	SVG_LIGHT: 'favicon.svg'
} as const;

// Substituted for `currentColor` in src/lib/assets/logo.svg when generating
// the light/dark static sources consumed by the PWA asset generator.
export const FAVICON_COLORS = {
	DARK: '#fafafa',
	LIGHT: '#111111'
} as const;

export const FAVICON_SELECTORS = {
	ICO_48X48: 'link[rel="icon"][sizes="48x48"]',
	SVG_ANY: 'link[rel="icon"][type="image/svg+xml"]'
} as const;

export const APPLE_ASSETS = {
	TOUCH_ICON: 'apple-touch-icon-180x180.png'
} as const;

export const PWA_MANIFEST = {
	background_color: THEME_COLORS.BACKGROUND_LIGHT,
	description: 'Local AI chat interface powered by llama.cpp',
	display: 'standalone' as const,
	icons: [
		{ sizes: '64x64', src: 'pwa-64x64.png', type: 'image/png' },
		{ sizes: '192x192', src: 'pwa-192x192.png', type: 'image/png' },
		{ purpose: 'any' as const, sizes: '512x512', src: 'pwa-512x512.png', type: 'image/png' },
		{
			purpose: 'maskable' as const,
			sizes: '512x512',
			src: 'maskable-icon-512x512.png',
			type: 'image/png'
		}
	],
	name: APP_NAME,
	short_name: APP_NAME,
	start_url: './',
	theme_color: THEME_COLORS.BACKGROUND_LIGHT
};

export const PWA_ICON_PATHS = {
	MASKABLE_512: '/maskable-icon-512x512.png',
	PWA_64: '/pwa-64x64.png',
	PWA_192: '/pwa-192x192.png',
	PWA_512: '/pwa-512x512.png'
} as const;

export const PWA_FILE_PATHS = {
	MANIFEST: '/manifest.webmanifest',
	SERVICE_WORKER: '/sw.js',
	VERSION: '/version.json',
	WORKBOX: '/workbox-<hash>.js'
} as const;

// Used by the server middleware to skip API key validation.
// Keep in sync with tools/server/server-http.cpp public_endpoints list.

export const PUBLIC_ENDPOINTS = [
	'/health',
	'/v1/health',
	'/models',
	'/v1/models',
	'/props',
	'/metrics',
	'/',
	'/index.html',

	'/favicon.ico',
	'/favicon-dark.ico',
	'/favicon.svg',
	'/favicon-dark.svg',
	'/pwa-64x64.png',
	'/pwa-192x192.png',
	'/pwa-512x512.png',
	'/maskable-icon-512x512.png',
	'/apple-touch-icon-180x180.png',
	'/manifest.webmanifest',
	'/sw.js',
	'/version.json',
	'/workbox-<hash>.js'
] as const;
export const BUILD_CONFIG = {
	GUIDE_COMMENT: `
<!--
  This is a static build of the frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
  To make changes, refer to the "Web UI" section in the README.
-->
`.trim(),
	OUTPUT_DIR: './dist'
} as const;

// PWA assets generator configuration — used by pwa-assets.config.ts
// FAVICON_PADDING: fraction (0..1) of the icon reserved as equal margin on
// each side. Applied to icon PNG/ICO outputs by @vite-pwa/assets-generator and
// post-processed into the static favicon.svg so the in-app logo (which reads
// src/lib/assets/logo.svg directly) is unaffected.
export const PWA_ASSET_GENERATOR = {
	FAVICON_PADDING: 0.04,
	LINK_PRESET: '2023'
} as const;

export const CACHE_SETTINGS = {
	API_CACHE_MAX_AGE_SECONDS: 60 * 60 * 24,
	API_CACHE_MAX_ENTRIES: 50,
	IMMUTABLE_MAX_AGE_SECONDS: 31536000,
	MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024
} as const;

export const GLOB_PATTERNS: string[] = [
	'**/*.{js,css,html,ico,svg,png,webp,woff,woff2,json,webmanifest}'
];

export const SW_CONFIG = {
	CHECK_INTERVAL_MS: 60000,
	UPDATE_FETCH_OPTIONS: {
		CACHE: 'no-store',
		HEADERS: {
			CACHE: 'no-store',
			CACHE_CONTROL: 'no-cache'
		}
	}
} as const;

// Runtime caching configuration for Workbox
export const RUNTIME_CACHING = {
	CACHE_NAME: 'api-cache',
	HANDLER: 'NetworkFirst'
} as const;

// Workbox runtime caching patterns
export const API_CACHING_PATTERNS = {
	STATIC_API: /^\/(health|props|models|tools|slots|cors-proxy).*/,
	V1_API: /^\/v1\/.*/
} as const;

// SvelteKit PWA plugin options
export const PWA_KIT_OPTIONS = {} as const;

export const APPLE_META_TAGS = {
	MOBILE_WEB_APP_CAPABLE: { content: 'yes', name: 'apple-mobile-web-app-capable' },
	MOBILE_WEB_APP_TITLE: { name: 'apple-mobile-web-app-title' },
	STATUS_BAR_STYLE: { content: 'black-translucent', name: 'apple-mobile-web-app-status-bar-style' }
} as const;

// SvelteKit PWA plugin configuration — used by @vite.config.ts
import type { SvelteKitPWAOptions } from '@vite-pwa/sveltekit';

export const SVELTEKIT_PWA_OPTIONS: SvelteKitPWAOptions = {
	devOptions: {
		enabled: true,
		suppressWarnings: true
	},

	// SvelteKit-specific options
	kit: {
		// Include version file for proper cache invalidation
		includeVersionFile: true
	},

	// Strategy: generateSW - the plugin generates a service worker automatically
	// using Workbox. For a custom SW, use 'injectManifest' instead.
	// Manifest configuration
	manifest: PWA_MANIFEST,

	// Workbox configuration for generateSW strategy
	workbox: {
		// Match all static assets in the build output.
		// Uses '**/' because SvelteKit outputs files under _app/immutable/
		// subdirectories.
		globPatterns: GLOB_PATTERNS,
		maximumFileSizeToCacheInBytes: CACHE_SETTINGS.MAX_FILE_SIZE_BYTES,

		// Prevent @vite-pwa/sveltekit from auto-adding a NavigationRoute by
		// setting navigateFallback to empty string. This keeps the service
		// worker from intercepting direct browser navigation to server API
		// endpoints (e.g. /slots, /models, /v1/models) which should return
		// JSON, not the SPA HTML shell. The server's own static-file fallback
		// handles non-API navigation to index.html for the SPA router.
		navigateFallback: '',

		// Runtime caching for API calls - use NetworkFirst so APIs are always fresh
		runtimeCaching: [
			{
				handler: RUNTIME_CACHING.HANDLER,
				options: {
					cacheName: RUNTIME_CACHING.CACHE_NAME,
					expiration: {
						maxAgeSeconds: CACHE_SETTINGS.API_CACHE_MAX_AGE_SECONDS,
						maxEntries: CACHE_SETTINGS.API_CACHE_MAX_ENTRIES
					}
				},
				urlPattern: API_CACHING_PATTERNS.V1_API
			},
			{
				handler: RUNTIME_CACHING.HANDLER,
				options: {
					cacheName: RUNTIME_CACHING.CACHE_NAME,
					expiration: {
						maxAgeSeconds: CACHE_SETTINGS.API_CACHE_MAX_AGE_SECONDS,
						maxEntries: CACHE_SETTINGS.API_CACHE_MAX_ENTRIES
					}
				},
				urlPattern: API_CACHING_PATTERNS.STATIC_API
			}
		]
	}
};
